language: node_js
node_js:
  - "0.10"
  - "0.8"
  - "0.6"
before_script:
  - wget http://s3.amazonaws.com/influxdb/influxdb_0.0.9_amd64.deb
  - sudo dpkg -i influxdb_latest_amd64.deb
script: npm run travis-test